name: Build
on: 
  pull_request:
  push:
  schedule:
    - cron: '0 7 1 * *'
permissions:
  write-all
jobs: 
  build:
    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-version: [ '8.0.x' ]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build Dotnet
        run: dotnet build && dotnet run
      - name: Publish Configuration
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Map Build"
          automatic_release_tag: latest
          prerelease: false
          files: |
            *.conf