name: Build
on: [pull_request, push]
jobs: 
  build:
    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@4
      - name: Setup Dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build Dotnet
        run: dotnet build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: 'false'
          files: |
            *.conf